### ISSUE TITLE
[FE] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by aaaz425** [codesquad-team4-issue-tracker/issue-tracker-max#1]
## Feature
프로젝트 초기 세팅

## Tasks
- [x] vite로 프로젝트 생성
- [x] 불필요한 파일 및 폴더 삭제
- [x] 의존성 설치(react-router-dom, emotion, prettier 등)
- [x] css reset
- [x] css base 작업 (font, color, logo, icon 등)
- [x] component 나누기
- [x] 라우팅 설정
