### ISSUE TITLE
[BE] 필터링을 추가한다.

### ISSUE THREAD

**Issue by JJONSOO** [codesquad-team4-issue-tracker/issue-tracker-max#29]
## Feature 
내가 단 코멘트의 이슈, 내가 담당된 이슈,  내가 작성한 이슈도 필터링을 한다.

## Tasks
- [ ] 내가 단 코멘트의 이슈
- [ ] 내가 담당된 이슈
- [ ]  내가 작성한 이슈
