### ISSUE TITLE
[BE] 이슈 작성 및 상세 페이지 테스트 코드 작성

### ISSUE THREAD

**Issue by Ojeegu** [codesquad-team4-issue-tracker/issue-tracker-max#31]
## Feature 
이슈 작성 및 상세 페이지 테스트 코드 작성

## Tasks
- [ ] 이슈 작성 기능 테스트 코드 작성
- [ ] 이슈 상세페이지 테스트 코드 작성
- [ ] 이슈 기능별 테스트 코드 작성
