### ISSUE TITLE
[FE] API 연동 및 2주차 리뷰 적용

### ISSUE THREAD

**Issue by aaaz425** [codesquad-team4-issue-tracker/issue-tracker-max#67]
## Feature 
API 연동 및 2주차 리뷰 적용

## Tasks
- [x] 이슈페이지 API 연동
- [x] 마일스톤페이지 API 연동
- [x] 레이블페이지 API 연동
- [x] 2주차 리뷰 적용(코드 리팩토링)
